name: Build & Test

env:
  GITHUB_IMAGE_NAME: 'ghcr.io/bp3/camunda-connectors'
  PROJECT_NAME: 'camunda-connectors'
  ORG_NAME: 'bp3'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  call-workflow-build-image:
    needs: build
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-image.yml
    with:
      username: ${{ github.actor }}
      project-name: ${{ env.PROJECT_NAME }}
      org-name: ${{ env.ORG_NAME }}
      image-name: ${{ env.GITHUB_IMAGE_NAME }}
      branch-name: ${{ github.head_ref || github.ref_name }}
    secrets: inherit

